version: "3"
services:
  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=Mgo
    volumes:
      - ./mongo-volume:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
  app_LMS:
    build: .
    ports: 
      - "8080:8080"
    depends_on:
      - mongo